const fields = [
  ['name', 'Your name', 'text', true], ['email', 'Email', 'email', true], ['phone', 'Phone', 'tel'],
  ['eventTitle', 'Event title', 'text', true], ['eventType', 'Type of celebration', 'select', false, ['Wedding', 'Private dinner', 'Birthday', 'Shower', 'Corporate event', 'Other']],
  ['eventDate', 'Event date (if known)', 'date'], ['venue', 'Venue and address', 'text'],
  ['setting', 'Event setting', 'select', false, ['Indoor', 'Outdoor', 'Both', 'Undecided']],
  ['guestCount', 'Estimated guests', 'number'], ['tableCount', 'Number of tables', 'number'],
  ['tableDetails', 'Table shapes, sizes, and seats per table', 'textarea'],
  ['budget', 'Styling / floral budget or range', 'text'],
  ['services', 'What would you like help with?', 'textarea', true],
  ['style', 'Style, mood, or theme', 'textarea'], ['palette', 'Color scheme, color names, or hex codes', 'text'],
  ['avoidColors', 'Colors or styles to avoid', 'text'],
  ['centerpieceHeight', 'Centerpiece height', 'select', false, ['Low / easy conversation', 'Tall', 'A mix of heights', 'Designer recommendation']],
  ['florals', 'Favorite flowers, greenery, or floral preferences', 'textarea'],
  ['tableware', 'Linens, plates, glassware, candles, and other details', 'textarea'],
  ['specialTables', 'Other areas to style (welcome, cake, sweetheart, gift tables)', 'textarea'],
  ['existingItems', 'What is already provided by you or the venue?', 'textarea'],
  ['restrictions', 'Allergies, accessibility needs, open-flame or venue restrictions', 'textarea'],
  ['timing', 'Event start/end, setup access, and teardown timing', 'textarea'],
  ['inspirationLinks', 'Inspiration or Atmos links (one per line)', 'textarea'],
  ['mustHaves', 'Must-haves, things to avoid, and other requests', 'textarea'],
  ['contactPreference', 'Preferred contact method', 'select', false, ['Email', 'Phone', 'Text']],
];
module.exports = { fields };
